# This file is covered by the LICENSE file in the root of this project.
# name: "sany"
labels:
  0: "material"
  1: "clapboard"
  2: "ground"
  3: "loader"
  4: "road-cone"
  5: "person"
  6: "instructure"
  7: "telegraph_poles"
  8: "tree"
  9: "charging_pile"
  10: "excavator"
  11: "speed_bumps"
  12: "other"
color_map: # bgr
  0: [0, 0, 0]
  1: [0, 0, 255]
  2: [245, 150, 100]
  3: [245, 230, 100]
  4: [250, 80, 100]
  5: [150, 60, 30]
  6: [255, 0, 0]
  7: [180, 30, 80]
  8: [255, 0, 0]
  9: [30, 30, 255]
  10: [200, 40, 255]
  11: [90, 30, 150]
  12: [255, 0, 255]
content: # as a ratio with the total number of points
  0: 0.0
  1: 0.1
  2: 0.2
  3: 0.1
  4: 0.2
  5: 0.2
  6: 0.1
  7: 0.2
  8: 0.2
  9: 0.1
  10: 0.1
  11: 0.1
  12: 0.1
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 1
  1: 2
  2: 3
  3: 4
  4: 5
  5: 6
  6: 7
  7: 8
  8: 9
  9: 10
  10: 11
  11: 12
  12: 0
learning_map_inv: # inverse of previous map
  0: 12
  1: 0
  2: 1
  3: 2
  4: 3
  5: 4
  6: 5
  7: 6
  8: 7
  9: 8
  10: 9
  11: 10
  12: 11
learning_ignore: # Ignoring classes before labels mapping. 
  0: False    # "unlabeled", and others ignored
  1: False
  2: False
  3: False
  4: False
  5: False
  6: False
  7: False
  8: False
  9: False
  10: False
  11: False
  12: True
split: # sequence numbers
  train:
    - 00
  valid:
    - 01
  test:
    - 02
