# This file is covered by the LICENSE file in the root of this project.
# name: "sany"
labels:
  0: "unlabeled"
  1: "ground"
  2: "instructure"
  3: "wall"
  4: "loader"
  5: "materialA"
  6: "materialB"
  7: "person"
  8: "other"
  9: "other"
color_map: # bgr
  0: [0, 0, 0]
  1: [150, 60, 30]
  2: [245, 150, 100]
  3: [245, 230, 100]
  4: [250, 80, 100]
  5: [0, 0, 255]
  6: [0, 255, 0]
  7: [255, 0, 0]
  8: [180, 30, 80]
  9: [180, 30, 80]
content: # as a ratio with the total number of points
  0: 0.0
  1: 0.1
  2: 0.2
  3: 0.1
  4: 0.2
  5: 0.1
  6: 0.1
  7: 0.1
  8: 0.1
  9: 0.1
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 0
  9: 0
learning_map_inv: # inverse of previous map
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False
  2: False
  3: False
  4: False
  5: False
  6: False
  7: False 
split: # sequence numbers
  train:
    - 00
  valid:
    - 01
  test:
    - 02
